name: novelPytorch
channels:
  - pyg
  - dglteam
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0=h5da7b33_2
  - absl-py=1.4.0=py38haa95532_0
  - aenum=3.1.15=pyhd8ed1ab_0
  - aext-assistant=0.4.0=py38h563a60c_jl3_0
  - aext-assistant-server=0.4.0=py38haa95532_0
  - aext-core=0.4.0=py38h563a60c_jl3_0
  - aext-core-server=0.4.0=py38haa95532_0
  - aext-shared=0.4.0=py38haa95532_0
  - aiohttp=3.9.0=py38h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - alembic=1.8.1=py38haa95532_0
  - anaconda-cloud-auth=0.1.4=py38haa95532_0
  - anaconda-toolbox=0.4.0=haa95532_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.5.0=py38haa95532_0
  - anytree=2.12.1=pyhd8ed1ab_0
  - aom=3.6.0=hd77b12b_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - arrow=1.2.3=py38haa95532_1
  - ase=3.22.1=pyhd8ed1ab_1
  - astroid=2.14.2=py38haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=23.1.0=py38haa95532_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - banal=1.0.6=pyhd8ed1ab_0
  - bcrypt=3.2.0=py38h2bbff1b_1
  - beautifulsoup4=4.12.2=py38haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=23.11.0=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py38haa95532_0
  - blosc=1.21.6=h85f69ea_0
  - boost-cpp=1.84.0=hce07faa_7
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py38hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.18.0=h91e5215_2
  - captum=0.6.0=pyhd8ed1ab_0
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.16.0=py38h2bbff1b_0
  - cfitsio=3.470=h2bbff1b_7
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38haa95532_0
  - cloudpickle=2.2.1=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.1.2=py38haa95532_0
  - console_shortcut=0.1.1=4
  - contourpy=1.0.5=py38h59b6b97_0
  - cookiecutter=2.5.0=py38haa95532_0
  - cpuonly=2.0=0
  - cryptography=41.0.7=py38h89fc84f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py38h2bbff1b_0
  - dask-core=2023.4.1=py38haa95532_0
  - dataset=1.6.2=pyhd8ed1ab_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dgl=2.2.1=py38_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.7=py38haa95532_0
  - docstring-to-markdown=0.11=py38haa95532_0
  - docutils=0.18.1=py38haa95532_3
  - entrypoints=0.4=py38haa95532_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=hac47afa_0
  - fastcache=1.1.0=py38he774522_0
  - flake8=6.0.0=py38haa95532_0
  - flask=2.2.5=py38haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h765892d_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.4.0=py38h2bbff1b_0
  - fsspec=2023.10.0=py38haa95532_0
  - future=0.18.3=py38haa95532_0
  - getopt-win32=0.1=h2bbff1b_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.86.0=ha3795fc_0
  - glib-tools=2.86.0=he647baa_0
  - glpk=5.0=h8ffe710_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - google-auth=2.22.0=py38haa95532_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=4.0.0=had6c3a3_0
  - greenlet=3.0.1=py38hd77b12b_0
  - grpc-cpp=1.48.2=h6772dbd_3
  - grpcio=1.48.2=py38h6772dbd_3
  - gtest=1.14.0=h59b6b97_0
  - gts=0.7.6=h63ab5a1_3
  - h11=0.12.0=pyhd3eb1b0_0
  - h2=4.0.0=py38haa95532_3
  - h5py=3.9.0=py38hfc34f40_0
  - harfbuzz=4.3.0=hb646838_2
  - hdf5=1.12.1=h1756f20_2
  - hpack=4.0.0=py_0
  - httpcore=0.15.0=py38haa95532_0
  - httpx=0.23.0=py38haa95532_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.4=py38haa95532_0
  - igraph=0.10.13=hb4b56bc_0
  - imagecodecs=2021.8.26=py38hc0a7faf_1
  - imageio=2.31.4=py38haa95532_0
  - imagesize=1.4.1=py38haa95532_0
  - importlib-metadata=7.0.1=py38haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py38haa95532_1
  - inflection=0.5.1=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.28.0=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isodate=0.6.1=py38haa95532_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py38haa95532_1
  - jellyfish=1.0.1=py38h36a85e1_0
  - jinja2=3.1.3=py38haa95532_0
  - joblib=1.2.0=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter_client=7.4.9=py38haa95532_0
  - jupyter_core=5.5.0=py38haa95532_0
  - jupyter_server=1.23.4=py38haa95532_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.2.2=py38haa95532_0
  - jupyterlab_server=2.25.1=py38haa95532_0
  - keyring=23.13.1=py38haa95532_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.4=py38hd77b12b_0
  - kneed=0.8.5=pyhd8ed1ab_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - leidenalg=0.10.2=py38h5e21985_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libavif=0.11.1=h2bbff1b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libboost=1.84.0=hb0986bb_7
  - libboost-devel=1.84.0=h91493d7_7
  - libboost-headers=1.84.0=h57928b3_7
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_h77d9078_1
  - libclang13=14.0.6=default_h77d9078_1
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.8=h8ffe710_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgd=2.3.3=ha43c60c_1
  - libglib=2.86.0=h5f26cbf_0
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libleidenalg=0.11.1=h91493d7_0
  - liblightgbm=4.5.0=cpu_hb4e115d_3
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=17.4=h4a159e6_2
  - libprotobuf=3.20.3=h12be248_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libsqlite=3.49.1=h67fdade_2
  - libssh2=1.10.0=he2ea4bf_2
  - libtiff=4.4.0=h8a3f274_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.12.7=h283a6d9_1
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=ha925a31_0
  - lightgbm=4.5.0=cpu_py_3
  - lightly=1.15.22=pyhd8ed1ab_0
  - lightly-utils=0.0.2=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=py38haa95532_0
  - llvmlite=0.41.0=py38hf2fb9eb_0
  - locket=1.0.0=py38haa95532_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.2.3=py38haa95532_0
  - markdown=3.4.1=py38haa95532_0
  - markdown-it-py=2.2.0=py38haa95532_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib=3.7.2=py38haa95532_0
  - matplotlib-base=3.7.2=py38h4ed8f06_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py38haa95532_0
  - mistune=2.0.4=py38haa95532_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - modal=0.4.1=pyhd8ed1ab_0
  - more-itertools=10.1.0=py38haa95532_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=he025d50_1002
  - mpmath=1.3.0=py38haa95532_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py38h2bbff1b_0
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=py38haa95532_0
  - nbclassic=0.5.5=py38haa95532_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.10.0=py38haa95532_0
  - nbformat=5.9.2=py38haa95532_0
  - nest-asyncio=1.5.6=py38haa95532_0
  - networkx=3.1=py38haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - notebook=6.5.4=py38haa95532_1
  - notebook-shim=0.2.3=py38haa95532_0
  - numba=0.58.1=py38hd77b12b_0
  - numexpr=2.8.4=py38h5b0cc5e_0
  - numpy=1.23.5=py38h3b20f71_0
  - numpy-base=1.23.5=py38h4da318b_0
  - numpydoc=1.5.0=py38haa95532_0
  - oauthlib=3.2.2=py38haa95532_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openpyxl=3.1.5=py38h827c3e9_0
  - openssl=3.5.4=h725018a_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.1=py38haa95532_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h78c2152_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38haa95532_0
  - pathspec=0.10.3=py38haa95532_0
  - patsy=0.5.3=py38haa95532_0
  - pcre=8.45=hd77b12b_0
  - pcre2=10.46=h3402e2f_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hd8e0db4_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pkce=1.0.3=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - platformdirs=3.10.0=py38haa95532_0
  - pluggy=1.0.0=py38haa95532_1
  - ply=3.11=py38_0
  - pooch=1.7.0=py38haa95532_0
  - poppler=22.12.0=h268424c_0
  - poppler-data=0.4.11=haa95532_1
  - powershell_shortcut=0.0.1=3
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - protobuf=3.20.3=py38hd77b12b_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pyclustering=0.10.1.2=py38hb1fd069_3
  - pycodestyle=2.10.0=py38haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py38h2bbff1b_1
  - pydocstyle=6.3.0=py38haa95532_0
  - pyflakes=3.0.1=py38haa95532_0
  - pygments=2.15.1=py38haa95532_1
  - pyjwt=2.4.0=py38haa95532_0
  - pylint=2.16.2=py38haa95532_0
  - pylint-venv=2.3.0=py38haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py38h8cc25b3_0
  - pynndescent=0.5.10=py38haa95532_0
  - pyopenssl=23.2.0=py38haa95532_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pyqtwebengine=5.15.10=py38hd77b12b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.19=h4de0772_0_cpython
  - python-annoy=1.17.3=py38h2698bfa_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=0.21.0=py38haa95532_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-igraph=0.11.6=py38h1747aac_0
  - python-louvain=0.16=pyhd8ed1ab_0
  - python-lsp-black=1.2.1=py38haa95532_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py38haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=7_cp38
  - pytoolconfig=1.2.6=py38haa95532_0
  - pytorch=1.12.1=cpu_py38h5e1f01c_1
  - pytorch-cluster=1.6.0=py38_torch_1.12.0_cpu
  - pytorch-lightning=2.0.3=py38haa95532_0
  - pytorch-mutex=1.0=cpu
  - pytorch_geometric=2.5.3=pyhd8ed1ab_0
  - pytz=2023.3.post1=py38haa95532_0
  - pywavelets=1.4.1=py38h2bbff1b_0
  - pywin32=305=py38h2bbff1b_0
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - pyzmq=24.0.1=py38h2bbff1b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py38haa95532_0
  - qt-main=5.15.2=h19c9488_12
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.2.2=py38haa95532_0
  - qtconsole=5.4.2=py38haa95532_0
  - qtpy=2.4.1=py38haa95532_0
  - rdflib=7.0.0=pyhd8ed1ab_0
  - re2=2022.04.01=hd77b12b_0
  - referencing=0.30.2=py38haa95532_0
  - requests=2.31.0=py38haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rfc3986=1.4.0=pyhd3eb1b0_0
  - rich=13.3.5=py38haa95532_0
  - rope=1.7.0=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=1.0.1=py38h2eaa2aa_0
  - scikit-image=0.19.3=py38hd77b12b_1
  - scikit-learn=1.3.0=py38h4ed8f06_1
  - scipy=1.10.1=py38h321e85e_0
  - seaborn=0.13.2=py38haa95532_0
  - semver=2.13.0=pyhd3eb1b0_0
  - send2trash=1.8.2=py38haa95532_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.0=py38haa95532_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38haa95532_0
  - sphinx=5.0.2=py38haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py38haa95532_1
  - spyder-kernels=2.4.4=py38haa95532_0
  - sqlalchemy=1.4.51=py38h2bbff1b_0
  - sqlite=3.49.1=h2466b09_2
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py38h9128911_0
  - sympy=1.5.1=py38_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.10.0=py38haa95532_0
  - tensorboard-data-server=0.6.1=py38haa95532_0
  - tensorboard-plugin-wit=1.8.1=py38haa95532_0
  - terminado=0.17.1=py38haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.11.2=pyhd8ed1ab_0
  - tinycss2=1.2.1=py38haa95532_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38haa95532_0
  - tomlkit=0.11.1=py38haa95532_0
  - toolz=0.12.0=py38haa95532_0
  - torchmetrics=1.1.2=py38haa95532_0
  - torchvision=0.15.2=cpu_py38h7187fe4_0
  - tornado=6.3.3=py38h2bbff1b_0
  - tqdm=4.65.0=py38hd4e2768_0
  - traitlets=5.7.1=py38haa95532_0
  - trimesh=4.1.0=pyhd8ed1ab_0
  - typing-extensions=4.9.0=py38haa95532_1
  - typing_extensions=4.9.0=py38haa95532_1
  - ucrt=10.0.22621.0=h57928b3_1
  - ujson=5.4.0=py38hd77b12b_0
  - umap-learn=0.5.4=py38haa95532_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.18=py38haa95532_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - watchdog=2.1.6=py38haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38haa95532_4
  - werkzeug=2.2.3=py38haa95532_0
  - whatthepatch=1.0.2=py38haa95532_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - wrapt=1.14.1=py38h2bbff1b_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.9.3=py38h2bbff1b_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=0.5.5=h0e60522_8
  - zipp=3.17.0=py38haa95532_0
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - gurobipy==11.0.3
      - treelib==1.7.1
prefix: C:\Users\Frederic.Ros\.conda\envs\novelPytorch
